package model;
// Generated Oct 26, 2018 5:26:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * NewPassengerRequest generated by hbm2java
 */
public class NewPassengerRequest  implements java.io.Serializable {


     private Integer requestId;
     private Route route;
     private User user;
     private String date;
     private String status;
     private Set passes = new HashSet(0);

    public NewPassengerRequest() {
    }

	
    public NewPassengerRequest(User user, String date, String status) {
        this.user = user;
        this.date = date;
        this.status = status;
    }
    public NewPassengerRequest(Route route, User user, String date, String status, Set passes) {
       this.route = route;
       this.user = user;
       this.date = date;
       this.status = status;
       this.passes = passes;
    }
   
    public Integer getRequestId() {
        return this.requestId;
    }
    
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }
    public Route getRoute() {
        return this.route;
    }
    
    public void setRoute(Route route) {
        this.route = route;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getPasses() {
        return this.passes;
    }
    
    public void setPasses(Set passes) {
        this.passes = passes;
    }




}


