package model;
// Generated Oct 26, 2018 5:26:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pass generated by hbm2java
 */
public class Pass  implements java.io.Serializable {


     private Integer passId;
     private NewPassengerRequest newPassengerRequest;
     private User user;
     private String issueAdte;
     private String validTill;
     private Set renewalRequests = new HashSet(0);
     private Set payments = new HashSet(0);

    public Pass() {
    }

    public Pass(NewPassengerRequest newPassengerRequest, User user, String issueAdte, String validTill, Set renewalRequests, Set payments) {
       this.newPassengerRequest = newPassengerRequest;
       this.user = user;
       this.issueAdte = issueAdte;
       this.validTill = validTill;
       this.renewalRequests = renewalRequests;
       this.payments = payments;
    }
   
    public Integer getPassId() {
        return this.passId;
    }
    
    public void setPassId(Integer passId) {
        this.passId = passId;
    }
    public NewPassengerRequest getNewPassengerRequest() {
        return this.newPassengerRequest;
    }
    
    public void setNewPassengerRequest(NewPassengerRequest newPassengerRequest) {
        this.newPassengerRequest = newPassengerRequest;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getIssueAdte() {
        return this.issueAdte;
    }
    
    public void setIssueAdte(String issueAdte) {
        this.issueAdte = issueAdte;
    }
    public String getValidTill() {
        return this.validTill;
    }
    
    public void setValidTill(String validTill) {
        this.validTill = validTill;
    }
    public Set getRenewalRequests() {
        return this.renewalRequests;
    }
    
    public void setRenewalRequests(Set renewalRequests) {
        this.renewalRequests = renewalRequests;
    }
    public Set getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set payments) {
        this.payments = payments;
    }




}


