package model;
// Generated Oct 26, 2018 5:26:26 PM by Hibernate Tools 4.3.1



/**
 * RenewalRequest generated by hbm2java
 */
public class RenewalRequest  implements java.io.Serializable {


     private Integer renewalRequest;
     private Pass pass;
     private Route route;
     private String date;
     private String status;

    public RenewalRequest() {
    }

    public RenewalRequest(Pass pass, Route route, String date, String status) {
       this.pass = pass;
       this.route = route;
       this.date = date;
       this.status = status;
    }
   
    public Integer getRenewalRequest() {
        return this.renewalRequest;
    }
    
    public void setRenewalRequest(Integer renewalRequest) {
        this.renewalRequest = renewalRequest;
    }
    public Pass getPass() {
        return this.pass;
    }
    
    public void setPass(Pass pass) {
        this.pass = pass;
    }
    public Route getRoute() {
        return this.route;
    }
    
    public void setRoute(Route route) {
        this.route = route;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


