package model;
// Generated Oct 26, 2018 5:26:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Route generated by hbm2java
 */
public class Route  implements java.io.Serializable {


     private Integer routeId;
     private String routeName;
     private String startPlace;
     private String endingPlace;
     private String otherDetails;
     private String stopDetails;
     private Set buses = new HashSet(0);
     private Set renewalRequests = new HashSet(0);
     private Set newPassengerRequests = new HashSet(0);

    public Route() {
    }

	
    public Route(String routeName, String startPlace, String endingPlace, String otherDetails) {
        this.routeName = routeName;
        this.startPlace = startPlace;
        this.endingPlace = endingPlace;
        this.otherDetails = otherDetails;
    }
    public Route(String routeName, String startPlace, String endingPlace, String otherDetails, String stopDetails, Set buses, Set renewalRequests, Set newPassengerRequests) {
       this.routeName = routeName;
       this.startPlace = startPlace;
       this.endingPlace = endingPlace;
       this.otherDetails = otherDetails;
       this.stopDetails = stopDetails;
       this.buses = buses;
       this.renewalRequests = renewalRequests;
       this.newPassengerRequests = newPassengerRequests;
    }
   
    public Integer getRouteId() {
        return this.routeId;
    }
    
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }
    public String getRouteName() {
        return this.routeName;
    }
    
    public void setRouteName(String routeName) {
        this.routeName = routeName;
    }
    public String getStartPlace() {
        return this.startPlace;
    }
    
    public void setStartPlace(String startPlace) {
        this.startPlace = startPlace;
    }
    public String getEndingPlace() {
        return this.endingPlace;
    }
    
    public void setEndingPlace(String endingPlace) {
        this.endingPlace = endingPlace;
    }
    public String getOtherDetails() {
        return this.otherDetails;
    }
    
    public void setOtherDetails(String otherDetails) {
        this.otherDetails = otherDetails;
    }
    public String getStopDetails() {
        return this.stopDetails;
    }
    
    public void setStopDetails(String stopDetails) {
        this.stopDetails = stopDetails;
    }
    public Set getBuses() {
        return this.buses;
    }
    
    public void setBuses(Set buses) {
        this.buses = buses;
    }
    public Set getRenewalRequests() {
        return this.renewalRequests;
    }
    
    public void setRenewalRequests(Set renewalRequests) {
        this.renewalRequests = renewalRequests;
    }
    public Set getNewPassengerRequests() {
        return this.newPassengerRequests;
    }
    
    public void setNewPassengerRequests(Set newPassengerRequests) {
        this.newPassengerRequests = newPassengerRequests;
    }




}


